deploymentName: accounts-deployment
serviceName: accounts
appLabel: accounts
appName: accounts

replicaCount: 2

image:
  repository: harry2276/accounts
  tag: s27

containerPort: 8080

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

appname_enabled: true
profile_enabled: true
config_enabled: true
discovery_enabled: true
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: false